name: Build and Release WPF App

on:
  push:
    tags:
      - 'v*'   

permissions: 
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  

      - name: Publish WPF app
        run: dotnet publish src/HamiltonVisualizer/HamiltonVisualizer.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o publish

      - name: Zip published files
        run: Compress-Archive -Path publish/* -DestinationPath Vraph-${{ github.ref_name }}.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: Vraph-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
