name: Build and Release WPF App

on:
  push:
    tags:
      - 'v*'    # Khi bạn tạo tag kiểu v1.0.0 thì trigger build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  

      - name: Publish WPF app
        run: dotnet publish YourProjectName.csproj -c Release -r win-x64 --self-contained true -o publish

      - name: Zip published files
        run: Compress-Archive -Path publish/* -DestinationPath MyApp-${{ github.ref_name }}.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: MyApp-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
